on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions
      - uses: secrethub/actions/env-export@master
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          SLACK_WEBHOOK: secrethub://florisvdg/demo/slack_webhook
          TEST_USERNAME: secrethub://florisvdg/demo/username
          TEST_SECRET: secrethub://florisvdg/demo/secret_with_newlines
      - run: echo "$TEST_SECRET"
      - name: Print environment with masked secrets
        run: printenv
      - name: Notify Slack
        uses: Ilshidur/action-slack@2.0.1 # this Action expects SLACK_WEBHOOK to be set
        with:
          args: |
            Hello from GitHub Actions 🚀
