on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/env-export
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          TEST_SECRET: secrethub://florisvdg/demo/secret_with_newlines
          USERNAME: secrethub://florisvdg/demo/username
      - run: |
          echo $USERNAME
          echo "$TEST_SECRET"
      - name: Print environment with masked secrets
        run: printenv
