on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions
      - uses: secrethub/actions/env-export@master
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          AWS_SECRET_ACCESS_KEY: secrethub://florisvdg/demo/username
          TEST_SECRET: secrethub://florisvdg/demo/secret_with_newlines
      - run: env | grep AWS_SECRET_ACCESS_KEY
      - name: Print environment with masked secrets
        run: printenv
